---
# file: 02-roles.yaml
- name: set up the IAM roles for the root structure
  hosts: roleadmin
  module_defaults:
    group/raphaeldegail.googlecloudy.gcp:
      auth_kind: '{{ auth_kind }}'
      access_token: '{{ access_token | default(omit) }}'
      service_account_contents: '{{ service_account_contents | default(omit) }}'
      service_account_email: '{{ service_account_email | default(omit) }}'
      service_account_file: '{{ service_account_file | default(omit) }}'
  vars_files:
    - definition.yaml

  roles:
    - name: get info about the organization
      role: gcp_org_info
      tags:
      - always
      - gcp
    - name: set up the IAM roles for the root structure
      role: gcp_role
      tags:
        - gcp
        - roles
