---
collections:
  - name: raphaeldegail.hcp_terraform
    version: 1.0.1
    type: galaxy
  - name: raphaeldegail.googlecloudy
    version: 1.0.1
    type: galaxy
  - name: google.cloud
    type: galaxy
  - name: community.general
    type: galaxy