---
argument_specs:
  main:
    short_description: Fetch info about a GCP organization from its domain name.
    description:
      - Fetch GCP info about an organization from its domain name.
      - The organization name and directory customer ID are retrieved.
    author:
      - Raphaël de Gail
    options:
      gcp_organization_domain:
        type: 'str'
        required: true
        description:
          - The domain name for the organization.
 