--- 
- name: list all available projects
  google.cloud.gcp_resourcemanager_project_info:
  register: all_projects

- name: filter projects with matching labels
  ansible.builtin.set_fact:
    hash_list: '{{ all_projects | community.general.json_query(query) }}'
  failed_when: "hash_list | length > 1"
  vars:
    query: "resources[?lifecycleState=='ACTIVE' && labels==`{{ root_project.labels | to_json }}`]"
