---
- name: create the GCP "executive" role
  raphaeldegail.googlecloudy.gcp_iam_organization_role:
    name: '{{ executive_role.name }}'
    title: '{{ executive_role.title }}'
    description: '{{ executive_role.description }}'
    included_permissions: '{{ executive_role.included_permissions }}'
    stage: '{{ executive_role.stage }}'
    organization_id: '{{ organization_id }}'

- name: create the GCP "workspace builder" role
  raphaeldegail.googlecloudy.gcp_iam_organization_role:
    name: '{{ builder_role.name }}'
    title: '{{ builder_role.title }}'
    description: '{{ builder_role.description }}'
    included_permissions: '{{ builder_role.included_permissions }}'
    stage: '{{ builder_role.stage }}'
    organization_id: '{{ organization_id }}'

- name: get the current access control policy for the GCP organization
  raphaeldegail.googlecloudy.gcp_resourcemanager_organization_iam_info:
    organization_id: '{{ organization_id }}'
  register: results

- name: update the current access control policy for the GCP organization
  raphaeldegail.googlecloudy.gcp_resourcemanager_organization_iam:
    bindings: '{{ results.bindings | union(extra_binding) }}'
    policy_version: '{{ policy_version }}'
    organization_id: '{{ organization_id }}'
  vars:
    extra_binding:
      - role: 'organizations/{{organization_id}}/roles/{{ executive_role.name }}'
        members:
          - 'group:{{ executive_group_email }}'
