---
argument_specs:
  main:
    short_description: Set up the roles for the dual structure
    description:
      - Create the organization executive role.
      - Create the workspace builder role.
    author:
      - Raphaël de Gail
    options:
      organization_id:
        type: 'str'
        required: true
        description:
          - The ID for the GCP organization.
      executive_role:
        type: 'dict'
        required: true
        description:
          - The definition of the organization executive role.
        options:
          name:
            type: 'str'
            required: true
            description:
              - The name of the role.
          title:
            type: 'str'
            required: false
            description:
              - The display name of the role.
          description:
            type: 'str'
            required: false
            description:
              - The description of the role.
          included_permissions:
            type: list
            required: true
            elements: 'str'
            description:
              - the list of permissions for the role.
          stage:
            type: 'str'
            required: true
            choices:
              - ALPHA
              - BETA
              - GA
              - DEPRECATED
              - DISABLED
              - EAP
            description:
              - The stage value for the role.
      builder_role:                 
        type: 'dict'
        required: true
        description:
          - The definition of the builder role.
        options:
          name:
            type: 'str'
            required: true
            description:
              - The name of the role.
          title:
            type: 'str'
            required: false
            description:
              - The display name of the role.
          description:
            type: 'str'
            required: false
            description:
              - The description of the role.
          included_permissions:
            type: list
            required: true
            elements: 'str'
            description:
              - the list of permissions for the role.
          stage:
            type: 'str'
            required: true
            choices:
              - ALPHA
              - BETA
              - GA
              - DEPRECATED
              - DISABLED
              - EAP
            description:
              - The stage value for the role.
      executive_group_email:
        type: 'str'
        required: true
        description:
          - The email address for the organization executives group.
