---
argument_specs:
  main:
    short_description: Initialize the organization IAM policy for the dual structure
    description:
      - Set up RBAC for basic groups of GCP organization.
      - The administrators group with roleAdmin and orgAdmin roles.
      - The finops group with finops role.
      - The organization policy group with policy role.
      - One external owner remains organization admin.
    author:
      - Raphaël de Gail
    options:
      organization_id:
        type: 'str'
        required: true
        description:
          - The ID for the GCP organization.
      finops_group_email:
        type: 'str'
        required: true
        description:
          - the finops group email address.
      admins_group_email:
        type: 'str'
        required: true
        description:
          - the administrators group email address.
      policy_group_email:
        type: 'str'
        required: true
        description:
          - the organization policy group email address.
      external_owner_email:
        type: 'str'
        required: true
        description:
          - the external owner email address.
