---
name: Deploy the dual structure
on:
  push:
    branches: [main, develop]
env:
  PYTHON_VERSION: '3.11'
jobs:
  playbook:
    runs-on: ubuntu-latest
    # Environment where integration variables are stored
    environment: develop
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: Set up Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install ansible collections
        run: ansible-galaxy collection install -r requirements.yml
      - name: Write ansible inventory
        run: |
          mkdir inventory;
          echo "---
          organization:
            vars:
              ansible_host: 127.0.0.1
              ansible_connection: local
              ansible_python_interpreter: ${{ steps.python.outputs.python-path }}
            hosts:
              hcpadmin:
          " > inventory/local.yml
      - name: Write integration-test configuration files
        env:
          CI_HCP_TERRAFORM_TOKEN: ${{ secrets.CI_HCP_TERRAFORM_TOKEN }}
          CI_HCP_TERRAFORM_ORG: ${{ vars.CI_HCP_TERRAFORM_ORG }}
          CI_HCP_TERRAFORM_PROJECT: ${{ secrets.CI_HCP_TERRAFORM_PROJECT }}
          CI_HCP_TERRAFORM_OAUTH: ${{ secrets.CI_HCP_TERRAFORM_OAUTH }} 
        run: |
          mkdir group_vars;
          echo "---
          organization_name: $CI_HCP_TERRAFORM_ORG
          bearer_token: $CI_HCP_TERRAFORM_TOKEN
          project: $CI_HCP_TERRAFORM_PROJECT
          oauth_token_id: $CI_HCP_TERRAFORM_OAUTH
          workspace:
            name: 'demo'
            description: 'Legendary Workstation workspace'
            budget_allowed: 10
            admin_group: 'nono@nono.nono'
            finops_group: 'nono@nono.nono'
            policy_group: 'nono@nono.nono'
            version: '~>1.7.0'
          " > group_vars/organization.yml
      # run tests
      - name: Run ansible playbook
        env:
          ANSIBLE_FORCE_COLOR: True
        run: ansible-playbook -v -i inventory/ site.yaml
